apiVersion: v1
kind: Service
metadata:
  name: devops-academy-service
spec:
  selector:
    app: devops-academy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
